### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by abhishekbatra** [okland/accounts-phone#1]
Hi,

As soon as I installed the library I received the following error in the running meteor instance:

> W20150218-15:27:04.894(5.5)? (STDERR) Error: A method named 'createUser' is already defined
W20150218-15:27:04.894(5.5)? (STDERR)     at packages/ddp/livedata_server.js:1444:1
W20150218-15:27:04.895(5.5)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
W20150218-15:27:04.895(5.5)? (STDERR)     at [object Object]._.extend.methods (packages/ddp/livedata_server.js:1442:1)
W20150218-15:27:04.895(5.5)? (STDERR)     at Package (packages/okland:accounts-phone/phone_server.js:543:1)

Please let me know how I can fix this.

Thanks,
Abhishek

**Comment by okland** [comment]
Hey,
Which other meteor packages do you use ?

**Comment by abhishekbatra** [comment]
Hey,

I have the following packages installed: 

> meteor-platform
urigo:angular
twbs:bootstrap
accounts-ui
angularui:angular-ui-router
accounts-password
aldeed:collection2
edgee:slingshot
random
meteorhacks:npm
npm-container
mdg:geolocation
okland:accounts-phone

**Comment by okland** [comment]
There was a problem of using the same name for meteor function "createUser" in okland:accounts-phone and accounts-password, i fixed it in version 0.0.8.

**Comment by abhishekbatra** [comment]
Hey,

It works fine now. Thanks a lot for the fixes! This issue can be closed I guess, maybe you can mark the commit here.

Abhishek
