### ISSUE TITLE
Error when using with twilio

### ISSUE THREAD

**Issue by shantanubhadoria** [okland/accounts-phone#10]
Thanks for this module.
I am running meteor 1.2.0 and I keep getting this error when using the requestPhoneVerification function on the client. The mobile number is valid and it only contains +, the country code and the mobile number following it(no dashes). 

    Exception in callback of async function: Error: [object Object] [Error sending SMS ]
    I20151006-17:15:24.277(8)?     at packages/okland_accounts-phone/packages/okland_accounts-phone.js:81:1
    I20151006-17:15:24.278(8)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)

**Comment by shantanubhadoria** [comment]
Please ignore this issue, it was a incorrect SID. On a side note more helpful error messages are probably a good idea.
Cheers!

**Comment by Garethderioth** [comment]
I have the same problem, and I'm sure that I using the correct SID. Do you have any example of the implementation?

**Comment by Animion** [comment]
Exactly the same problem. I'm sure my SID is correct.

**Comment by netors** [comment]
Same issue here:

    => App running at: http://localhost:3000/
    I20151101-14:10:26.537(-8)? Exception in callback of async function: Error: [object Object] [Error sending SMS ]
    I20151101-14:10:26.538(-8)?     at packages/okland_accounts-phone/packages/okland_accounts-phone.js:81:1
    I20151101-14:10:26.538(-8)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)

I'm sure I'm using the correct SID,TOKEN and FROM number, I tested sending messages using curl and it works.

Also, I am not even seeing any Failed API calls at the Usage tab on Twilio

**Comment by veeramarni** [comment]
I have same issue .

Below are the settings i use
```
SMS.twilio = {
    ACCOUNT_SID: Meteor.settings.TWILIO.SID,
    AUTH_TOKEN: Meteor.settings.TWILIO.TOKEN
};
if (Meteor.settings && Meteor.settings.ACCOUNTS_PHONE) {
    Accounts._options.adminPhoneNumbers = Meteor.settings.ACCOUNTS_PHONE.ADMIN_NUMBERS;
    Accounts._options.phoneVerificationMasterCode = Meteor.settings.ACCOUNTS_PHONE.MASTER_CODE;
    Meteor.settings.ACCOUNTS_PHONE.RETRIES && (Accounts._options.verificationMaxRetries = Meteor.settings.ACCOUNTS_PHONE.RETRIES);
}
```

And in Meteor Settings file
```
{
  "TWILIO": {
    "FROM": "appname",
    "SID": "xxxxx",
    "TOKEN": "xxxx"
  },
  "ACCOUNTS_PHONE": {
    "ADMIN_NUMBERS": ["123456789", "987654321"],
    "MASTER_CODE": "1234",
    "RETRIES" : 20
  },
}
```
Error
```
I20151207-14:22:32.735(-5)? Exception in callback of async function: Error: [object Object] [Error sending SMS ]
I20151207-14:22:32.736(-5)?     at packages/okland_accounts-phone/packages/okland_accounts-phone.js:81:1
I20151207-14:22:32.736(-5)?     at Meteor.bindEnvironment.runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
```

**Comment by Garethderioth** [comment]
This one worked for me: https://github.com/DispatchMe/meteor-accounts-sms
