### ISSUE TITLE
Add and Remove Phones

### ISSUE THREAD

**Issue by zhaoyao91** [okland/accounts-phone#16]
Thanks for this package, we can build a simple phone account system. but I think there should be some server side helpers like add phones and remove phones to help build more flexible system.

**Comment by ahmedtabrez** [comment]
I don't know whether the owner (@okland) is actively maintaining this project, but take a look at [my fork](https://github.com/ahmedtabrez/accounts-phone/) or my [pull request](https://github.com/okland/accounts-phone/pull/12). I have added `Accounts.changeUserPhone()` which of course needs a lil optimization.

**Comment by zhaoyao91** [comment]
@ahmedtabrez I will follow it. 3q
