### ISSUE TITLE
Please fix the typo in the project description.

### ISSUE THREAD

**Issue by josephdburdick** [okland/accounts-phone#2]
Sorry to be a nag but...it bugs me. "Meteor" is misspelled in the repo description. :bulb:

**Comment by okland** [comment]
Ok :), do you mean "meteor" to "Meteor" ?

**Comment by josephdburdick** [comment]
No I mean "A login service based on mobile phone number for *Metoer*" 
Meteor here is misspelled.

**Comment by okland** [comment]
Fixed ! Tnx.

**Comment by josephdburdick** [comment]
:+1:
